# Generated by Django 2.2.19 on 2022-02-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220208_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='address',
            new_name='slug',
        ),
    ]
